### ISSUE TITLE
Add a strict mode which dies on cpanfiles containing unparseable constructs

### ISSUE THREAD

**Issue by jwrightecs** [PerlServices/CPANfile-Parse-PPI#1]
Should add a strict mode (or make the module strict-only), that stops the parsing of mixed perl code / cpanfile syntax,   something like
```
for my $module (qw/
        IO::All
        Zydeco::Lite::App
/) {
        requires $module, '0';
}

```
which returns this list of modules currently:
```
[
  {
    'name' => '$module',
    'stage' => '',
    'type' => 'requires',
    'version' => '0'
  }
]

```

**Comment by jwrightecs** [comment]
Alternatively it could bail on the $prereq node not being a PPI::Token::Quote or being a PPI::Token::Quote::Interpolate node with a value that requires interpolation

**Comment by reneeb** [comment]
This sounds like a good idea.

**Comment by reneeb** [comment]
Does 58f049e looks good to you?

**Comment by jwrightecs** [comment]
Looks good to me

**Comment by reneeb** [comment]
I released a new version shipping the new strict mode.
